-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Customer"
(
    cust_id character varying,
    cust_name character varying(50) NOT NULL,
    contact integer NOT NULL,
    address character varying(100) NOT NULL,
    city character varying(50) NOT NULL,
    postcode integer NOT NULL,
    PRIMARY KEY (cust_id)
);

CREATE TABLE IF NOT EXISTS public."Order"
(
    order_id character varying,
    cust_id character varying,
    delivery_emp_id character varying,
    order_date date NOT NULL,
    shipper_id character varying,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public."OrderDetails"
(
    orderdetails_id character varying,
    order_id character varying,
    product_id character varying,
    qty integer NOT NULL,
    PRIMARY KEY (orderdetails_id)
);

CREATE TABLE IF NOT EXISTS public."Product"
(
    product_id character varying,
    product_name character varying(50) NOT NULL,
    supplier_id integer,
    category_id character varying,
    price integer NOT NULL,
    expirydate date,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public."Suppliers"
(
    supplier_id integer,
    supplier_name character varying(50) NOT NULL,
    contact integer NOT NULL,
    city character varying(50) NOT NULL,
    address character varying(100) NOT NULL,
    postcode integer NOT NULL,
    PRIMARY KEY (supplier_id)
);

CREATE TABLE IF NOT EXISTS public."Categories"
(
    category_id character varying,
    category_name character varying(50) NOT NULL,
    description character varying(200) NOT NULL,
    PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public."Shippers"
(
    shipper_id character varying,
    shipper_name character varying(50) NOT NULL,
    contact integer NOT NULL,
    PRIMARY KEY (shipper_id)
);

CREATE TABLE IF NOT EXISTS public."Employee"
(
    emp_id character varying,
    emp_name character varying(50) NOT NULL,
    contact integer NOT NULL,
    vehicle character varying(50) NOT NULL,
    address character varying(100) NOT NULL,
    office character varying(100) NOT NULL,
    PRIMARY KEY (emp_id)
);

ALTER TABLE IF EXISTS public."Order"
    ADD CONSTRAINT cust_id FOREIGN KEY (cust_id)
    REFERENCES public."Customer" (cust_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Order"
    ADD CONSTRAINT shipper_id FOREIGN KEY (shipper_id)
    REFERENCES public."Shippers" (shipper_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Order"
    ADD CONSTRAINT delivery_emp_id FOREIGN KEY (delivery_emp_id)
    REFERENCES public."Employee" (emp_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OrderDetails"
    ADD CONSTRAINT order_id FOREIGN KEY (order_id)
    REFERENCES public."Order" (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OrderDetails"
    ADD CONSTRAINT product_id FOREIGN KEY (product_id)
    REFERENCES public."Product" (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Product"
    ADD CONSTRAINT supplier_id FOREIGN KEY (supplier_id)
    REFERENCES public."Suppliers" (supplier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Product"
    ADD CONSTRAINT category_id FOREIGN KEY (category_id)
    REFERENCES public."Categories" (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;